name: build-pdfs


on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build & Deploy to GitHub Pages
      env:
        SUBFOLDER: transparencias
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        PUBLISH_TO_BRANCH: gh-pages
        BASE_URL: https://bbddetsisi.github.io/material-docente/
      uses: laracabrera/marp-action@master
